import type { Container } from './types';

export const INITIAL_CONTAINERS: Container[] = [
  {
    id: 'calls',
    name: 'Places to Call / Email',
    size: 'big',
    items: [
      { id: 'call-1', text: 'Cadence Academy', subSteps: [], completed: false },
      {
        id: 'call-2',
        text: 'Anthem – Brown Health Bill',
        details: 'Due date: 6/25/2026 · Amount due: $180.70 · Date of service: 5/27/2026 · Patient: Leo Figueriedo',
        subSteps: [],
        completed: false,
      },
      { id: 'call-3', text: 'Rheumatology', subSteps: [], completed: false },
      { id: 'call-4', text: 'Sleep Study', subSteps: [], completed: false },
      { id: 'call-5', text: 'Dr. Lasher – Hematology', subSteps: [], completed: false },
      { id: 'call-6', text: "Cancel Cloaked – tell them it's not working", subSteps: [], completed: false },
      { id: 'call-7', text: 'UNT Payroll', subSteps: [], completed: false },
      { id: 'call-8', text: 'RI Insurance agent once registered', subSteps: [], completed: false },
      { id: 'call-9', text: 'Anthem – Propanolol', subSteps: [], completed: false },
      { id: 'call-10', text: 'Leo VG – supplies, teacher, orientation', subSteps: [], completed: false },
    ],
  },
  {
    id: 'otelier',
    name: 'Otelier',
    size: 'big',
    items: [
      { id: 'ot-1', text: 'Print Project sheet', subSteps: [], completed: false },
      {
        id: 'ot-fsad',
        text: 'FSAD',
        subSteps: [
          { id: 'ot-fsad-1', text: 'Skills / agent', completed: false },
          { id: 'ot-fsad-2', text: 'Demo prep w/ Ishara', completed: false },
          { id: 'ot-fsad-3', text: 'UX audit agent', completed: false },
          { id: 'ot-fsad-4', text: 'Prism hosting', completed: false },
          { id: 'ot-fsad-5', text: 'Install g grid', completed: false },
          { id: 'ot-fsad-6', text: 'Install minimal UI', completed: false },
        ],
        completed: false,
      },
      { id: 'ot-vai', text: 'VAI mapping (Nick)', subSteps: [], completed: false },
      {
        id: 'ot-4', text: 'MCR fix Giftshop', completed: false,
        subSteps: [
          { id: 'ot-4-1', text: 'Mapping update', completed: false },
        ],
      },
      {
        id: 'sys-manager',
        text: 'System Manager redesign',
        subSteps: [
          { id: 'sm-1', text: 'AI prototype', completed: false },
          { id: 'sm-2', text: 'Usability test mockups', completed: false },
          { id: 'sm-3', text: 'Refine mocks based on feedback', completed: false },
          { id: 'sm-4', text: 'Readout presentation', completed: false },
          { id: 'sm-5', text: 'Tree testing software', completed: false },
        ],
        completed: false,
      },
      {
        id: 'onboarding',
        text: 'Onboarding',
        subSteps: [
          { id: 'ob-1', text: 'Map MCR', completed: false },
          { id: 'ob-2', text: 'Map Section L', completed: false },
          { id: 'ob-3', text: 'Map Piatt', completed: false },
          { id: 'ob-4', text: 'Map Fess Parker', completed: false },
          { id: 'ob-4b', text: 'Fess Parker mapping update', completed: false },
          { id: 'ob-5', text: 'Map VAI', completed: false },
          { id: 'ob-6', text: 'Documentation', completed: false },
          { id: 'ob-7', text: 'Cross training', completed: false },
        ],
        completed: false,
      },
    ],
    sections: [
      {
        id: 'redesigns',
        label: 'Redesigns (for later)',
        items: [
          { id: 'rd-1', text: 'DigiAudit, Rec, IntelliSight, TPX audit' },
          { id: 'rd-2', text: 'Health center' },
          { id: 'rd-3', text: 'Notification stack > between app notifs' },
          { id: 'rd-4', text: 'CRM shift to SM' },
        ],
      },
    ],
  },
  {
    id: 'chores',
    name: 'Chores',
    size: 'big',
    items: [
      { id: 'ch-0', text: 'Pay water bill', subSteps: [], completed: false },
      { id: 'ch-1', text: 'Daily chore print', subSteps: [], completed: false },
      { id: 'ch-2', text: 'Clean up computer', subSteps: [], completed: false },
      { id: 'ch-3', text: 'Clean out fridge', subSteps: [], completed: false },
      { id: 'ch-4', text: 'Clean toilets', subSteps: [], completed: false },
      { id: 'ch-5', text: 'Laundry', subSteps: [], completed: false },
      { id: 'ch-6', text: 'Donation(s)', subSteps: [], completed: false },
      { id: 'ch-7', text: 'School pack', subSteps: [], completed: false },
      {
        id: 'ch-8', text: "Auggie's room", completed: false,
        subSteps: [
          { id: 'ch-8-1', text: 'Hang pics', completed: false },
          { id: 'ch-8-2', text: 'Blackout curtains', completed: false },
          { id: 'ch-8-3', text: 'Remove coats', completed: false },
        ],
      },
      {
        id: 'ch-9', text: "Leo's room", completed: false,
        subSteps: [
          { id: 'ch-9-1', text: 'Remove coats', completed: false },
        ],
      },
      {
        id: 'ch-10', text: 'E&A room', completed: false,
        subSteps: [
          { id: 'ch-10-1', text: 'Blackout curtains', completed: false },
          { id: 'ch-10-2', text: 'Jewelry', completed: false },
          { id: 'ch-10-3', text: 'Declutter', completed: false },
        ],
      },
      {
        id: 'ch-11', text: 'Upper hallway', completed: false,
        subSteps: [
          { id: 'ch-11-1', text: 'Fix rugs', completed: false },
          { id: 'ch-11-2', text: 'Hang artwork', completed: false },
        ],
      },
      { id: 'ch-12', text: 'Hang hallway pics', subSteps: [], completed: false },
      { id: 'ch-13', text: 'Move kitty litter', subSteps: [], completed: false },
      { id: 'ch-14', text: 'Humidifiers', subSteps: [], completed: false },
      { id: 'ch-15', text: 'Medicines prep', subSteps: [], completed: false },
      { id: 'ch-16', text: 'Print lists', subSteps: [], completed: false, evan: true },
      { id: 'ch-17', text: 'Empty upstairs trash', subSteps: [], completed: false },
      { id: 'ch-18', text: 'Big recycling box in living room', subSteps: [], completed: false },
      { id: 'ch-19', text: 'Water plants', subSteps: [], completed: false },
      { id: 'ch-20', text: 'Wash bedding', subSteps: [], completed: false },
      { id: 'ch-21', text: 'Makeup organization', subSteps: [], completed: false },
      { id: 'ch-22', text: 'Guest room organization', subSteps: [], completed: false },
      { id: 'ch-23', text: 'Trump account registration', subSteps: [], completed: false },
      { id: 'ch-24', text: 'Email cleanup', subSteps: [], completed: false },
      { id: 'ch-25', text: 'Beach towel move', subSteps: [], completed: false },
      { id: 'ch-26', text: 'Traffic bill pay', subSteps: [], completed: false },
      { id: 'ch-27', text: 'Hospital bill pay', subSteps: [], completed: false },
    ],
  },
  {
    id: 'personal',
    name: 'Personal',
    size: 'big',
    items: [
      { id: 'per-vac', text: 'Vacuum seal winterwear', subSteps: [], completed: false },
      { id: 'per-ac', text: 'Clean AC Units', subSteps: [], completed: false },
      {
        id: 'per-1',
        text: 'Update death doc',
        subSteps: [
          { id: 'per-1-1', text: 'Transfer to Claude', completed: false },
          { id: 'per-1-2', text: 'Update to include: Stessa, landlord accts, Allstate, healthcare, school daycares', completed: false },
          { id: 'per-1-3', text: 'Print and send to Mom, B/Lee — keep a copy', completed: false },
        ],
        completed: false,
      },
      { id: 'per-2', text: 'Upload IG saves & screenshots to Claude and delete', subSteps: [], completed: false },
      { id: 'per-3', text: "Clean up online storage (iPhone, Evan's, drives — export to MixBook and DVDs as needed)", subSteps: [], completed: false },
      { id: 'per-4', text: 'Start Xmas gifts – kids art Mixbook', subSteps: [], completed: false },
      { id: 'per-5', text: 'Review IG following list and transfer to Claude', subSteps: [], completed: false },
      { id: 'per-6', text: 'Add Niantic and recent IG saves to NE Bucket List', subSteps: [], completed: false },
      {
        id: 'per-7',
        text: 'Skincare routine',
        subSteps: [
          { id: 'per-7-1', text: 'Determine a low and high routine', completed: false },
          { id: 'per-7-2', text: 'Print email attachment', completed: false },
          { id: 'per-7-3', text: 'Print steps', completed: false },
          { id: 'per-7-4', text: 'Buy products needed', completed: false },
        ],
        completed: false,
      },
      {
        id: 'per-8',
        text: 'Set up Minimals phone',
        subSteps: [
          { id: 'per-8-1', text: 'Charge phone', completed: false },
          { id: 'per-8-2', text: 'Find walk-through video', completed: false },
          { id: 'per-8-3', text: 'Prepare to go to T-Mobile', completed: false },
        ],
        completed: false,
      },
      { id: 'per-9', text: 'Libby sync', subSteps: [], completed: false },
      { id: 'per-10', text: 'Robo vac schedule', subSteps: [], completed: false },
      { id: 'per-11', text: 'Video doorbell', subSteps: [], completed: false },
      { id: 'per-12', text: 'Car registration appt', subSteps: [], completed: false },
      { id: 'per-13', text: 'Organize playroom', subSteps: [], completed: false },
      {
        id: 'per-14',
        text: 'Hall bathroom',
        subSteps: [
          { id: 'per-14-1', text: 'Toothbrush charging station', completed: false },
        ],
        completed: false,
      },
      {
        id: 'per-15',
        text: 'Living room',
        subSteps: [
          { id: 'per-15-1', text: 'Drawer organization', completed: false },
          { id: 'per-15-2', text: 'Firestick', completed: false },
        ],
        completed: false,
      },
      { id: 'per-16', text: 'Cord management', subSteps: [], completed: false },
      { id: 'per-17', text: 'Baba veterinarian', subSteps: [], completed: false },
      { id: 'per-18', text: 'Mechanic', subSteps: [], completed: false },
      { id: 'per-19', text: 'CVS', subSteps: [], completed: false },
      { id: 'per-20', text: 'Move guitar', subSteps: [], completed: false },
      { id: 'per-21', text: 'Keyboard plug', subSteps: [], completed: false },
      { id: 'per-22', text: 'Photo cleanup', subSteps: [], completed: false },
      {
        id: 'per-bike', text: 'Bike readiness', completed: false,
        subSteps: [
          { id: 'per-bike-1', text: "Auggie seat install", completed: false },
          { id: 'per-bike-2', text: 'Leo bars install', completed: false },
          { id: 'per-bike-3', text: 'Auggie helmet', completed: false },
          { id: 'per-bike-4', text: 'Phone mount install', completed: false },
        ],
      },
      { id: 'per-23', text: 'Add photos to shared album', subSteps: [], completed: false },
      { id: 'per-24', text: 'Update New England bucket list', subSteps: [], completed: false },
      { id: 'per-25', text: 'Ask Alex about breakfast', subSteps: [], completed: false },
      { id: 'per-26', text: 'Goodwill run', subSteps: [], completed: false },
      { id: 'per-27', text: 'Empty old pot on balcony', subSteps: [], completed: false },
    ],
  },
  {
    id: 'health',
    name: 'Health',
    size: 'medium',
    items: [
      {
        id: 'hlth-1',
        text: 'Build easy recipe library from IG – maybe do the freezer thing',
        subSteps: [
          { id: 'hlth-1-1', text: 'Figure out how Claude can support – saving recipes, agentic push to Instacart', completed: false },
          { id: 'hlth-1-2', text: 'Find one or two recipes from Instagram and add', completed: false },
        ],
        completed: false,
      },
      {
        id: 'hlth-2',
        text: 'Glucose monitoring',
        subSteps: [
          { id: 'hlth-2-1', text: 'Review purchases in Gmail', completed: false },
          { id: 'hlth-2-2', text: 'Buy equipment needed', completed: false },
          { id: 'hlth-2-3', text: 'Add to checklists / daily routines as needed', completed: false },
        ],
        completed: false,
      },
      { id: 'hlth-3', text: 'Print simple IG workout & mobility/stretch routine', subSteps: [], completed: false },
      { id: 'hlth-4', text: 'Autoimmune / chronic conditions from IG', subSteps: [], completed: false },
    ],
  },
  {
    id: 'kids',
    name: 'Kids',
    size: 'medium',
    items: [
      { id: 'kids-1', text: "Write Leo's teacher", subSteps: [], completed: false },
      { id: 'kids-2', text: "Leo's next appt on calendar", subSteps: [], completed: false },
      { id: 'kids-3', text: "Boys' dentist appts on calendar", subSteps: [], completed: false },
      { id: 'kids-4', text: 'Gymnastics research', subSteps: [], completed: false },
    ],
  },
  {
    id: 'unt',
    name: 'UNT',
    size: 'medium',
    items: [
      { id: 'unt-1', text: "Read Teagan's articles", subSteps: [], completed: false },
      { id: 'unt-2', text: 'Add checklist items here', subSteps: [], completed: false },
      { id: 'unt-3', text: 'Memo grading web app', subSteps: [], completed: false },
      { id: 'unt-4', text: 'Memo video assignments', subSteps: [], completed: false },
      { id: 'unt-5', text: 'PW recovery', subSteps: [], completed: false },
      { id: 'unt-6', text: 'Tegan fall question', subSteps: [], completed: false },
      { id: 'unt-7', text: 'Lucero email', subSteps: [], completed: false },
    ],
  },
  {
    id: 'travel',
    name: 'Travel',
    size: 'medium',
    items: [
      {
        id: 'tr-nyc',
        text: 'NYC',
        subSteps: [
          { id: 'tr-nyc-1', text: 'Buy train tickets', completed: false },
          { id: 'tr-nyc-2', text: 'Book lodging', completed: false },
          { id: 'tr-nyc-3', text: 'Pre-purchase attractions (Groupons, City Pass, etc.)', completed: false },
        ],
        completed: false,
      },
      {
        id: 'tr-girls',
        text: 'Girls trip',
        subSteps: [
          { id: 'tr-girls-1', text: 'Dates on calendar', completed: false },
          { id: 'tr-girls-2', text: 'Child arrangements', completed: false },
          { id: 'tr-girls-3', text: 'Flights', completed: false },
        ],
        completed: false,
      },
      { id: 'tr-4', text: 'Update address on any flights after move date', subSteps: [], completed: false },
      { id: 'tr-5', text: 'Call AA / Delta etc. to change address on upcoming tickets', subSteps: [], completed: false },
      { id: 'tr-6', text: "Update everyone's AA / Delta address", subSteps: [], completed: false },
    ],
  },
  {
    id: 'to-buy',
    name: 'To Buy',
    size: 'medium',
    items: [
      { id: 'buy-1', text: 'Warm bulbs for guest room', subSteps: [], completed: false },
      { id: 'buy-2', text: 'Iron supplement', subSteps: [], completed: false },
      { id: 'buy-3', text: 'Meatballs', subSteps: [], completed: false },
      { id: 'buy-4', text: 'Pasta noodles', subSteps: [], completed: false },
      { id: 'buy-5', text: 'Easy mac', subSteps: [], completed: false },
      { id: 'buy-6', text: 'Butter', subSteps: [], completed: false },
      { id: 'buy-7', text: 'Bananas', subSteps: [], completed: false },
      { id: 'buy-8', text: 'Oranges', subSteps: [], completed: false },
      { id: 'buy-9', text: 'Grapes', subSteps: [], completed: false },
    ],
  },
  {
    id: 'finances',
    name: 'Finances',
    size: 'medium',
    items: [
      {
        id: 'fin-1',
        text: 'Update auto payments from Autumn to go to Ev – Omaha, Allstate, First American, etc.',
        subSteps: [
          { id: 'fin-1-1', text: 'Review automatic payments / delete unwanted', completed: false },
        ],
        completed: false,
      },
      { id: 'fin-2', text: "Add Autumn to Evan's Chase acct", subSteps: [], completed: false },
      { id: 'fin-3', text: "Close Autumn's Chase acct", subSteps: [], completed: false },
      { id: 'fin-4', text: 'Transaction audit', subSteps: [], completed: false },
      { id: 'fin-5', text: 'Activate Santander card', subSteps: [], completed: false },
      { id: 'fin-6', text: 'Order new card for Evan', subSteps: [], completed: false },
    ],
  },
  {
    id: 'writing',
    name: 'Writing',
    size: 'medium',
    items: [
      { id: 'writ-1', text: 'Write first draft of Armadillo', subSteps: [], completed: false },
    ],
  },
];
